# Generated by Django 4.1.7 on 2023-03-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_company', models.CharField(max_length=120)),
                ('job_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=120)),
                ('job_salary', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_avalaible', models.BooleanField(default=True)),
            ],
        ),
    ]
