# Generated by Django 4.1.7 on 2023-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='job_avalaible',
            new_name='job_available',
        ),
    ]
